# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: advent-of-code-2023
spec:
  type: website
  lifecycle: production
  owner: developers
